@echo off
echo Starting Python server with TUNNEL_MODE=True...
start "Python Server" cmd /k "set TUNNEL_MODE=True&& cd healthanaly && python app.py"
echo Starting localtunnel...
npx localtunnel --port 5000 --subdomain healthllm
